datetimeFormat: rfc1123
defaultBranch: ""
defaultChannel: ""
channels:
  datetimeFormat: test
  maxVersionHistoryLength: 0
  pausePromotion: false
  notificationConfig: {}
promotions:
  datetimeFormat: ""
  notificationConfig: {}
git: {}
