channels:
    maxversionhistorylength: 30
    notificationconfig:
        slackconfig:
            slackchannel: ""
    pausepromotion: false
datetimeformat: rfc1123
defaultbranch: ""
defaultchannel: ""
git:
    gittype: ""
promotions:
    notificationconfig:
        slackconfig:
            slackchannel: ""
