datetimeFormat: ""
defaultBranch: ""
defaultChannel: ""
channels:
  maxVersionHistoryLength: 0
  pausePromotion: false
  notificationConfig:
    slackConfig:
      slackChannel: ""
promotions:
  notificationConfig:
    slackConfig:
      slackChannel: ""
git:
  gitType: ""
