package v1

const (
	// Github actions default
	DEFAULT_GITHUB_ACTIONS_DIRECTORY_PATH = ".github"

	DEFAULT_GITHUB_ACTIONS_PRE_PROMOTION_WORKFLOW_NAME  = "pre-promotion"
	DEFAULT_GITHUB_ACTIONS_PROMOTION_WORKFLOW_NAME      = "promotion"
	DEFAULT_GITHUB_ACTIONS_POST_PROMOTION_WORKFLOW_NAME = "post-promotion"
)
