package constants

const (
	// GitLab actions default
	DEFAULT_GITLAB_PIPELINE_DIRECTORY_PATH = ".gitlab"

	DEFAULT_GITLAB_PIPELINE_PRE_PROMOTION_WORKFLOW_NAME  = "pre-promotion"
	DEFAULT_GITLAB_PIPELINE_PROMOTION_WORKFLOW_NAME      = "promotion"
	DEFAULT_GITLAB_PIPELINE_POST_PROMOTION_WORKFLOW_NAME = "post-promotion"
)
